name: Nix Flake Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-and-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Update nixpkgs input
        run: nix flake lock --update-input nixpkgs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto-update Flake
          commit_user_name: Update Bot
          commit_user_email: actions@github.com
          commit_author: Update Bot <actions@github.com>
